### ISSUE TITLE
github flow

### ISSUE THREAD

**Issue by yaseiva** [spaceagetv/electron-playwright-helpers#68]
I'm not sure why on ubuntu its failing , is there anything special we need to do?

TypeError: Cannot read properties of undefined (reading 'close')

      39 |
      40 | test.afterAll(async () => {
    > 41 |   await electronApp.close()
         |                     ^
      42 | })

e2e-workflow:

```yaml
name: 'Tests: E2E'

on: [pull_request]

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [20]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            commandPrefix: 'xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" --'
          - os: windows-latest
            commandPrefix: ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: e2e tests
         run: ${{ matrix.commandPrefix }} yarn e2e

```
